- name: Create ibmtpm directory
  file:
    path: /root/ibmtpm
    state: directory

- name: Download and unarchive ibmtpm
  unarchive:
    src: http://sourceforge.net/projects/ibmswtpm2/files/ibmtpm1119.tar.gz
    dest: /root/ibmtpm
    remote_src: yes

- name: Compile tpm emulator
  make:
      chdir: /root/ibmtpm/src/

- name: Install tpm_server
  command: install -c /root/ibmtpm/src/tpm_server /usr/local/bin/tpm_server

- name: Install init_tpm_server script
  command: install -c /root/keylime/swtpm2_scripts/init_tpm_server /usr/local/bin/init_tpm_server

- name: Install tpm_serverd script
  command: install -c /root/keylime/swtpm2_scripts/tpm_serverd /usr/local/bin/tpm_serverd

- name: Changing perm of "tpm_serverd", adding "+x"
  file: dest=/usr/local/bin/tpm_serverd mode=a+x

- name: Changing perm of "init_tpm_server", adding "+x"
  file: dest=/usr/local/bin/init_tpm_server mode=a+x

- name: 'Set environment'
  shell: "echo $TPM2TOOLS_TCTI"
  environment:
    TPM2TOOLS_TCTI: "tabrmd:bus_name=com.intel.tss2.Tabrmd"

- name: Start TPM Emulator
  command: /usr/local/bin/tpm_serverd
  become: yes

- name: enable service tpm2_abrmd and ensure it is not masked
  systemd:
    name: tpm2-abrmd
    enabled: yes
    masked: no

- name: Change TCTI to emulator
  lineinfile:
    path: /usr/lib/systemd/system/tpm2-abrmd.service
    regexp: '^ExecStart='
    line: ExecStart=/usr/sbin/tpm2-abrmd --tcti=mssim

- name: Reload / restart service tpm2-abrmd, in all cases
  systemd:
    name: tpm2-abrmd
    state: restarted
    daemon_reload: yes
    
#
# - name: reload service tpm2-abrmd, in all cases
#   systemd:
#     name: tpm2-abrmd
#     state: reloaded
#
# - name: Make sure a service is running
#   systemd:
#     state: started
#     name: tpm2-abrmd
