- name: update/upgrade all packages
  dnf:
      name: "*"
      state: latest

- name: install prerequisite packages
  dnf:
      name:
        - git
        - automake
        - libtool
        - autoconf
        - autoconf-archive
        - libstdc++-devel
        - gcc
        - pkg-config
        - uriparser-devel
        - libgcrypt-devel
        - dbus-devel
        - glib2-devel
        - compat-openssl10-devel
        - libcurl-devel
        - python3-pip
        - python3-pyyaml
        - python3-m2crypto
        - python3-tornado
        - python3-simplejson
        - python3-requests
        - python3-sqlalchemy
        - python3-alembic
        - libselinux-python3
        - yaml-cpp-devel
        - procps-ng
        - tpm2-tss
        - tpm2-tools
        - tpm2-abrmd
        - python3-zmq
      state: latest
