- name: update/upgrade all packages
  dnf:
      name: "*"
      state: latest

- name: install git
  dnf:
      name: git
      state: latest

- name: install automake
  dnf:
      name: automake
      state: latest

- name: install libtool
  dnf:
      name: libtool
      state: latest

- name: install autoconf
  dnf:
      name: autoconf
      state: latest

- name: install autoconf-archive
  dnf:
      name: autoconf-archive
      state: latest

- name: install libstdc++-devel
  dnf:
      name: libstdc++-devel
      state: latest

- name: install gcc
  dnf:
      name: gcc
      state: latest

- name: install pkg-config
  dnf:
      name: pkg-config
      state: latest

- name: install uriparser-devel
  dnf:
      name: uriparser-devel
      state: latest

- name: install libgcrypt-devel
  dnf:
      name: libgcrypt-devel
      state: latest

- name: install dbus-devel
  dnf:
      name: dbus-devel
      state: latest

- name: install glib2-devel
  dnf:
      name: glib2-devel
      state: latest

- name: install compat-openssl10-devel
  dnf:
      name: compat-openssl10-devel
      state: latest

- name: install libcurl-devel
  dnf:
      name: libcurl-devel
      state: latest

- name: install PyYAML
  dnf:
      name: PyYAML
      state: latest
